# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^notebooks/'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
        - id: mypy
          exclude: notebooks
          additional_dependencies: [pydantic, types-requests, types-python-dateutil]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: notebooks

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        exclude: notebooks
        additional_dependencies: [tomli]

-   repo: https://github.com/tconbeer/sqlfmt
    rev: v0.18.0
    hooks:
    -   id: sqlfmt
        language_version: python

#-   repo: https://github.com/sqlfluff/sqlfluff
#    rev: 2.1.0
#    hooks:
#    -   id: sqlfluff-lint
#        additional_dependencies: [dbt-bigquery, sqlfluff-templater-dbt]
#        args: [--dialect, "bigquery", --exclude-rules, "L036"]
